# Generated by Django 5.1.5 on 2025-01-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='details_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
