# Generated by Django 5.1.5 on 2025-01-25 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_details_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='details_url',
        ),
    ]
