# Generated by Django 6.0.4 on 2026-04-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_remove_package_details_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO Description', null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO Title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique URL identifier', max_length=255, null=True, unique=True),
        ),
    ]
