# Generated by Django 5.1.1 on 2025-01-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('id_proof_number', models.CharField(max_length=50)),
                ('preferred_date', models.DateField()),
                ('preferred_shift', models.CharField(max_length=50)),
                ('alternative_dates', models.TextField(help_text='List alternative dates separated by commas.')),
                ('number_of_adults', models.PositiveIntegerField()),
                ('number_of_children', models.PositiveIntegerField()),
                ('preferred_duration', models.CharField(max_length=50)),
                ('accommodation_help', models.BooleanField(default=False)),
                ('accommodation_preferences', models.TextField(blank=True, null=True)),
                ('pickup_drop_service', models.BooleanField(default=False)),
                ('special_requests', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
