# Generated by Django 5.1.1 on 2025-01-21 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='id_proof_number',
            new_name='Any_Govt_ID_number',
        ),
    ]
