# Generated by Django 5.1.5 on 2025-01-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_id_proof_number_booking_any_govt_id_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_of_adults', models.PositiveIntegerField()),
                ('number_of_children', models.PositiveIntegerField()),
                ('preferred_duration', models.CharField(max_length=50)),
                ('accommodation_help', models.BooleanField(default=False)),
                ('accommodation_preferences', models.TextField(blank=True, null=True)),
                ('pickup_drop_service', models.BooleanField(default=False)),
                ('special_requests', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='accommodation_help',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='accommodation_preferences',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='number_of_adults',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='number_of_children',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pickup_drop_service',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='preferred_duration',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='special_requests',
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_package',
            field=models.CharField(choices=[('Jim Corbett Jungle Safari', 'Jim Corbett Jungle Safari'), ('Neem Karoli Mandir', 'Neem Karoli Mandir'), ('Chardham Yatra', 'Chardham Yatra'), ('Adventure Package', 'Adventure Package')], default='Jim Corbett Jungle Safari', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_packages',
            field=models.ManyToManyField(blank=True, help_text='Select one or more packages.', to='booking.packageoption'),
        ),
    ]
