# Generated by Django 5.1.5 on 2025-01-22 08:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_packageoption_remove_booking_accommodation_help_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Any_Govt_ID_number',
            new_name='preferred_duration',
        ),
        migrations.RemoveField(
            model_name='packageoption',
            name='accommodation_help',
        ),
        migrations.RemoveField(
            model_name='packageoption',
            name='accommodation_preferences',
        ),
        migrations.RemoveField(
            model_name='packageoption',
            name='number_of_adults',
        ),
        migrations.RemoveField(
            model_name='packageoption',
            name='number_of_children',
        ),
        migrations.RemoveField(
            model_name='packageoption',
            name='pickup_drop_service',
        ),
        migrations.RemoveField(
            model_name='packageoption',
            name='preferred_duration',
        ),
        migrations.RemoveField(
            model_name='packageoption',
            name='special_requests',
        ),
        migrations.AddField(
            model_name='booking',
            name='accommodation_help',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='accommodation_preferences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='govt_id_number',
            field=models.CharField(default='NOT_PROVIDED', max_length=50, verbose_name='Government ID Number'),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_adults',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_children',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_drop_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='selected_package',
            field=models.CharField(choices=[('Jim Corbett Jungle Safari', 'Jim Corbett Jungle Safari'), ('Neem Karoli Mandir', 'Neem Karoli Mandir'), ('Chardham Yatra', 'Chardham Yatra'), ('Adventure Package', 'Adventure Package')], default='Jim Corbett Jungle Safari', help_text='Select a single package from the options.', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='selected_packages',
            field=models.ManyToManyField(blank=True, help_text='Select one or more additional packages.', to='booking.packageoption'),
        ),
    ]
