# Generated by Django 5.1.5 on 2025-01-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_rename_any_govt_id_number_booking_preferred_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_of_adults',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_children',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
