# Generated by Django 5.1.5 on 2025-01-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_number_of_adults_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='govt_id_number',
            field=models.CharField(default='UNKNOWN_ID', max_length=50, verbose_name='Government ID Number'),
        ),
    ]
