# Generated by Django 5.1.5 on 2025-01-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_govt_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='govt_id_number',
            field=models.CharField(default='---------', max_length=50, verbose_name='Government ID Number'),
        ),
    ]
