# Generated by Django 5.1.5 on 2025-01-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_booking_govt_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='govt_id_other',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Specify Other ID Type'),
        ),
        migrations.AddField(
            model_name='booking',
            name='govt_id_type',
            field=models.CharField(choices=[('Aadhaar Card', 'Aadhaar Card'), ('PAN Card', 'PAN Card'), ('Passport', 'Passport'), ('Voter ID', 'Voter ID'), ('Driving License', 'Driving License'), ('Other', 'Other')], default='Aadhaar Card', max_length=50, verbose_name='Government ID Type'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='govt_id_number',
            field=models.CharField(max_length=50, verbose_name='Government ID Number'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.IntegerField(max_length=12),
        ),
    ]
