# Generated by Django 5.1.5 on 2025-01-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_booking_govt_id_other_booking_govt_id_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='selected_packages',
        ),
        migrations.AlterField(
            model_name='booking',
            name='govt_id_number',
            field=models.CharField(default='---------', max_length=50, verbose_name='Government ID Number'),
        ),
    ]
