# Generated by Django 5.1.5 on 2025-01-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_remove_booking_selected_packages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='selected_package',
            field=models.CharField(choices=[('Jim Corbett Jungle Safari', 'Jim Corbett Jungle Safari'), ('Neem Karoli Mandir', 'Neem Karoli Mandir'), ('Chardham Yatra', 'Chardham Yatra'), ('Adventure Package', 'Adventure Package')], help_text='Select a single package from the options.', max_length=50),
        ),
    ]
