# Generated by Django 5.1.5 on 2025-01-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_hotelbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel_images/')),
                ('alt_text', models.CharField(max_length=255)),
            ],
        ),
    ]
