# Generated by Django 5.1.5 on 2025-01-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_carouselimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
