# Generated by Django 5.1.1 on 2025-01-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='media/gallery/'),
        ),
        migrations.AlterField(
            model_name='heroimage',
            name='image',
            field=models.ImageField(upload_to='media/hero/'),
        ),
        migrations.AlterField(
            model_name='safaripackage',
            name='image',
            field=models.ImageField(upload_to='media/packages/'),
        ),
    ]
