# Generated by Django 5.1.1 on 2025-01-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_galleryimage_image_alter_heroimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safaripackage',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
