# Generated by Django 5.1.5 on 2025-01-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_safaripackage_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a short title for the image', max_length=255)),
                ('image', models.ImageField(help_text='Upload the image file', upload_to='gallery/')),
                ('description', models.TextField(blank=True, help_text='Optional: Add a description for the image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
