# Generated by Django 5.1.5 on 2025-01-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_gallery_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Gallery', 'verbose_name_plural': 'GalleryPG'},
        ),
    ]
