# Generated by Django 5.1.5 on 2025-01-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_gallery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='safaripackage',
            name='details_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
