# Generated by Django 5.1.5 on 2025-01-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_safaripackage_details_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safaripackage',
            name='details_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
