# Generated by Django 6.0.4 on 2026-04-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_safaripackage_details_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='seo_caption',
            field=models.CharField(blank=True, help_text='SEO rich caption for image', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='safaripackage',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Primary keyword for SEO', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='safaripackage',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO Description', null=True),
        ),
        migrations.AddField(
            model_name='safaripackage',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO Title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='safaripackage',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique URL identifier', max_length=255, null=True, unique=True),
        ),
    ]
