# Generated by Django 6.0.4 on 2026-04-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_galleryimage_seo_caption_safaripackage_focus_keyword_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTravelAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_slug', models.SlugField(help_text="Unique page identifier (e.g., 'home', 'jim-corbett', 'neem-karoli')", max_length=100, unique=True)),
                ('agent_name', models.CharField(default='Travel Guide', help_text="Name of the bot for this page (e.g., 'Ranger Rahul')", max_length=150)),
                ('agent_avatar', models.ImageField(blank=True, help_text='Custom avatar image for the chat widget', null=True, upload_to='media/agent_avatars/')),
                ('theme_color', models.CharField(default='#007BFF', help_text='Hex color code for the chat bubbles on this page', max_length=20)),
                ('teaser_messages', models.JSONField(default=list, help_text="List of short popup strings (e.g., ['👋 Hi!', 'Need help?'])")),
                ('greeting_messages', models.JSONField(default=list, help_text='Full greeting messages when chatbot opens')),
                ('suggested_prompts', models.JSONField(default=list, help_text="Actionable chat chips for users (e.g., ['Show Pricing', 'Itinerary limits?'])")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dynamic Travel Agent',
                'verbose_name_plural': 'Dynamic Travel Agents',
                'ordering': ['page_slug'],
            },
        ),
    ]
